services:
  app:
    image: ruby
    container_name: myapp
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 3000:3000
    depends_on:
      - db_dev
    command: bash -c "bundle install && ruby db/start_database.rb && ruby app/server.rb"
  db_dev:
    image: postgres
    container_name: development_db
    environment:
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_USER=myuser
      - POSTGRES_DB=devdb
    volumes:
      - relabs_data_dev:/var/lib/postgresql/data
  test:
    image: ruby
    container_name: myapp_test
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db_test
    command: bash -c "bundle install && rspec && rubocop"
  db_test:
    image: postgres
    container_name: test_db
    environment:
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_USER=myuser
      - POSTGRES_DB=testdb
    volumes:
      - relabs_data_test:/var/lib/postgresql/data
volumes:
  relabs_data_dev:
  relabs_data_test:
