services:
  api:
    image: ruby
    container_name: api
    volumes:
      - ./api:/api
    working_dir: /api
    ports:
      - 4000:4000
    depends_on:
      - db_dev
    command: bash -c "bundle install --without test && ruby db/start_database.rb && ruby app/server.rb"
    environment:
      - REDIS_URL=redis://redis:6379/0

  sidekiq:
    image: ruby
    container_name: sidekiq
    volumes:
      - ./api:/api
    working_dir: /api
    environment:
      - REDIS_URL=redis://redis:6379/0
    ports:
      - 9292:9292
    depends_on:
      - api
      - redis
    command: bash -c "bundle install --without test && sidekiq -r ./app/jobs/import_csv_job.rb"

  redis:
    container_name: redis
    image: redis

  db_dev:
    image: postgres
    container_name: development_db
    environment:
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_USER=myuser
      - POSTGRES_DB=devdb
    volumes:
      - relabs_data_dev:/var/lib/postgresql/data

  test_api:
    image: ruby
    container_name: test_api
    volumes:
      - ./api:/api
    working_dir: /api
    depends_on:
      - db_test
    command: bash -c "bundle install && rspec && rubocop"

  db_test:
    image: postgres
    container_name: test_db
    environment:
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_USER=myuser
      - POSTGRES_DB=testdb

  web:
    build: ./web
    container_name: web
    volumes:
      - ./web:/web
    ports:
      - 3000:3000
    depends_on:
      - db_dev
      - api
    environment:
      - BROWSER_PATH=/usr/bin/google-chrome
    command: bash -c "bundle install --without test && ruby app/server.rb"

  test_web:
    build: ./web
    container_name: test_web
    volumes:
      - ./web:/web
    depends_on:
      - db_test
      - test_api
    environment:
      - BROWSER_PATH=/usr/bin/google-chrome
    command: bash -c "bundle install && bundle exec rspec && rubocop"

volumes:
  relabs_data_dev:
