services:
  app: &app_base
    image: ruby
    container_name: myapp
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 3000:3000
      - 9292:9292
    depends_on:
      - db_dev
      - redis
    command: bash -c "bundle install && ruby db/start_database.rb && ruby app/server.rb"
    environment:
      - REDIS_URL=redis://redis:6379/0

  sidekiq:
    <<: *app_base
    container_name: sidekiq
    ports: []
    depends_on:
      - redis
    command: bash -c "bundle install && sidekiq -r ./app/jobs/import_csv_job.rb"

  redis:
    container_name: redis
    image: redis

  db_dev:
    image: postgres
    container_name: development_db
    environment:
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_USER=myuser
      - POSTGRES_DB=devdb
    volumes:
      - relabs_data_dev:/var/lib/postgresql/data

  test:
    image: ruby
    container_name: myapp_test
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db_test
    command: bash -c "bundle install && rspec && rubocop"

  db_test:
    image: postgres
    container_name: test_db
    environment:
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_USER=myuser
      - POSTGRES_DB=testdb

volumes:
  relabs_data_dev:
