source 'https://rubygems.org'

gem 'csv'
gem 'faraday', '~> 2.0'
gem 'pg'
gem 'puma'
gem 'rack-cors'
gem 'rubocop'
gem 'sidekiq'
gem 'sinatra'
group :test do
  gem 'capybara'
  gem 'rack-test'
  gem 'rspec'
  gem 'simplecov', require: false
end
